apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: siddharth
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:7.0
          name: mongo
          imagePullPolicy: IfNotPresent
          resources: {}

          # create a use in mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: mongo-root-password

          volumeMounts:
            - name: mongodb-storage #must match with volume-template-name
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

  # works as a pvc but create it for each pod
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
