apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
  namespace: siddharth
spec:
  ports:
    - name: 8080-80
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend-deployment
  type: ClusterIP
