sonar.projectKey=google-photo-backend
sonar.projectName=Google Photo Backend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js,**/*.spec.js,**/coverage/**

# Encoding
sonar.sourceEncoding=UTF-8
