apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: siddharth
spec:
  provider: aws
  parameters:
    region: "us-east-1"
    usePodIdentity: "true"
    preferredAddressType: "ipv4"
    objects: |
      - objectName: "google-photo-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "\"mongo-root-username\""
            objectAlias: "mongo-root-username"
          - path: "\"mongo-root-password\""
            objectAlias: "mongo-root-password"
          - path: "\"MONGO_URI\""
            objectAlias: "MONGO_URI"
          - path: "\"aws_access_key_id\""
            objectAlias: "aws_access_key_id"
          - path: "\"aws_secret_access_key\""
            objectAlias: "aws_secret_access_key"
  secretObjects:
    - secretName: google-photo-secrets
      type: Opaque
      data:
        - objectName: mongo-root-username
          key: mongo-root-username
        - objectName: mongo-root-password
          key: mongo-root-password
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: aws_access_key_id
          key: aws_access_key_id
        - objectName: aws_secret_access_key
          key: aws_secret_access_key