# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: aws-secrets
#   namespace: siddharth
# spec:
#   provider: aws
#   parameters:
#     usePodIdentity: "true"
#     objects: |
#       - objectName: "google-photo-secrets"
#         objectType: "secretsmanager"

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: siddharth
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    preferredAddressType: "ipv4"
    objects: |
      - objectName: "google-photo-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "mongo-root-username"
            objectAlias: "mongo-root-username"
          - path: "mongo-root-password"
            objectAlias: "mongo-root-password"
  secretObjects:
    - secretName: google-photo-secrets
      type: Opaque
      data:
        - objectName: mongo-root-username
          key: mongo-root-username
        - objectName: mongo-root-password
          key: mongo-root-password