apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: siddharth
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "google-photo-secrets"
        objectType: "secretsmanager"
