name: Frontend - Scan, Build Image & Upload

on:
  push:
    branches: 
      - master
    paths: 
      - 'frontend-main/**'
  workflow_dispatch:

jobs:

  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://3.86.198.228:9000/
        with:
          projectBaseDir: frontend-main

      # - name: Debug - list scannerwork folder
      #   run: ls -la frontend-main/.scannerwork/ || echo "folder not found"

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        with:
          scanMetadataReportFile: frontend-main/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://3.86.198.228:9000
          

  build:
    needs: sonarqube
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend-main/package-lock.json

      - name: Install dependencies
        working-directory: frontend-main
        run: npm ci

      - name: Build app
        working-directory: frontend-main
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: frontend-main/dist/
          retention-days: 7