name: Frontend - Scan, Build Image & Upload

on:
  push:
    branches: 
      - master
    paths: 
      - 'frontend-main/**'
  workflow_dispatch:

jobs:

  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://3.86.198.228:9000/
        with:
          projectBaseDir: frontend-main

      # - name: Debug - list scannerwork folder
      #   run: ls -la frontend-main/.scannerwork/ || echo "folder not found"

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        with:
          scanMetadataReportFile: frontend-main/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://3.86.198.228:9000
          

  docker:
      needs: sonarqube
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set short SHA
          id: vars
          run: echo "short_sha=${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"

        - name: Build image (local, not pushed yet)
          uses: docker/build-push-action@v6
          with:
            context: frontend-main
            push: false
            load: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-main:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-main:${{ steps.vars.outcome.short_sha }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Trivy vulnerability scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-main:${{ steps.vars.outcome.short_sha }}
            format: table
            severity: CRITICAL,HIGH
            exit-code: '1'

        - name: Push image (only if scan passed)
          uses: docker/build-push-action@v6
          with:
            context: frontend-main
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-main:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-main:${{ steps.vars.outcome.short_sha }}
            cache-from: type=gha